Librerias

In [8]:
pip install pandas

Requirement already satisfied: pandas in c:\users\jaime\appdata\local\programs\python\python312\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\jaime\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jaime\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\jaime\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\jaime\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\jaime\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [9]:
import pandas as pd

In [4]:
# Leer el archivo CSV
df = pd.read_csv('medical_condition.csv')

# Convertir el DataFrame a JSON
df.to_json('diagnostico_medico.json', orient='records', lines=True)

In [ ]:
# Leer el archivo JSON
df = pd.read_json('diagnostico_medico.json', lines=True)

# Convertir el DataFrame a CSV
df.to_csv('Diag_medico.csv', index=False)

In [11]:
df2 = pd.read_json('diagnostico_medico.json', lines=True)
df2

,id,full_name,age,gender,smoking_status,bmi,blood_pressure,glucose_levels,condition
0,1,User0001,53,male,Non-Smoker,27.400000,135.100000,135.300000,Pneumonia
1,2,User0002,30,male,Non-Smoker,27.400000,105.315064,135.800000,Diabetic
2,3,User0003,18,male,Non-Smoker,35.612486,135.100000,135.300000,Pneumonia
3,4,User0004,53,male,Non-Smoker,27.400000,99.119829,135.300000,Pneumonia
4,5,User0005,76,male,Non-Smoker,27.400000,135.100000,135.800000,Diabetic
...,...,...,...,...,...,...,...,...,...
9995,9996,User9996,53,male,Non-Smoker,25.029002,152.540355,137.551451,Pneumonia
9996,9997,User9997,54,male,Non-Smoker,27.017487,135.100000,135.800000,Diabetic
9997,9998,User9998,23,male,Smoker,27.400000,148.833321,173.931480,Pneumonia
9998,9999,User9999,53,female,Non-Smoker,27.400000,135.100000,135.300000,Pneumonia
9999,10000,User10000,27,male,Non-Smoker,25.454891,135.100000,196.083267,Diabetic

In [ ]:
df=pd.read_csv('medical_condition.csv')
df

,id,full_name,age,gender,smoking_status,bmi,blood_pressure,glucose_levels,condition
0,1,User0001,53.0,male,Non-Smoker,27.400000,135.100000,135.300000,Pneumonia
1,2,User0002,30.0,male,Non-Smoker,27.400000,105.315064,135.800000,Diabetic
2,3,User0003,18.0,male,Non-Smoker,35.612486,135.100000,135.300000,Pneumonia
3,4,User0004,53.0,male,Non-Smoker,27.400000,99.119829,135.300000,Pneumonia
4,5,User0005,76.0,male,Non-Smoker,27.400000,135.100000,135.800000,Diabetic
...,...,...,...,...,...,...,...,...,...
9995,9996,User9996,53.0,male,Non-Smoker,25.029002,152.540355,137.551451,Pneumonia
9996,9997,User9997,54.0,male,Non-Smoker,27.017487,135.100000,135.800000,Diabetic
9997,9998,User9998,23.0,male,Smoker,27.400000,148.833321,173.931480,Pneumonia
9998,9999,User9999,53.0,female,Non-Smoker,27.400000,135.100000,135.300000,Pneumonia
9999,10000,User10000,27.0,male,Non-Smoker,25.454891,135.100000,196.083267,Diabetic

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              10000 non-null  int64
 1   full_name       10000 non-null  object
 2   age             10000 non-null  float64
 3   gender          10000 non-null  object
 4   smoking_status  10000 non-null  object
 5   bmi             10000 non-null  float64
 6   blood_pressure  10000 non-null  float64
 7   glucose_levels  10000 non-null  float64
 8   condition       10000 non-null  object
dtypes: float64(4), int64(1), object(4)
memory usage: 703.3+ KB

In [13]:
df.columns

Index(['id', 'full_name', 'age', 'gender', 'smoking_status', 'bmi',
       'blood_pressure', 'glucose_levels', 'condition'],
      dtype='object')

In [14]:
df["gender"].unique()

array(['male', 'female'], dtype=object)

In [7]:
df2.describe()

                id           age           bmi  blood_pressure  glucose_levels
count  10000.00000  10000.000000  10000.000000    10000.000000    10000.000000
mean    5000.50000     53.503300     27.410895      135.215051      135.227916
std     2886.89568     15.448037      4.931850       15.981353       25.944846
min        1.00000     18.000000     15.012119       90.009620       70.015961
25%     2500.75000     50.000000     27.400000      135.100000      132.800000
50%     5000.50000     54.000000     27.400000      135.100000      135.800000
75%     7500.25000     56.250000     27.400000      135.900000      135.800000
max    10000.00000     89.000000     39.998687      179.999359      199.890429